// You are given three positive integers num1, num2, and num3.

// The key of num1, num2, and num3 is defined as a four-digit number such that:

// Initially, if any number has less than four digits, it is padded with leading zeros.
// The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
// Return the key of the three numbers without leading zeros (if any).

struct Solution;
impl Solution {
    pub fn generate_key(num1: i32, num2: i32, num3: i32) -> i32 {
        let mut ans = 0i32;
        let mut nums = [num1, num2, num3];

        for d in 0u32..=3u32 {
          let mut min_digit = i32::MAX;

          for mut num in nums.iter_mut() {
            if *num == 0 {
              return ans;
            }
            if *num % 10 < min_digit{
              min_digit = *num % 10;
            }
            *num /= 10;
          }
          ans += min_digit * 10i32.pow(d);
        }
        ans
    }
}

    // pub fn generate_key(num1: i32, num2: i32, num3: i32) -> i32 {
    //     let mut nums = [
    //         format!("{:04}", num1),
    //         format!("{:04}", num2),
    //         format!("{:04}", num3),
    //     ];

    //     let mut key = String::new();

    //     for i in 0..4 {
    //         let min_digit = nums.iter().map(|s| s.chars().nth(i).unwrap())
    //                             .min().unwrap();
    //         key.push(min_digit);
    //     }

    //     key.parse::<i32>().unwrap()
    // }

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_1() {
      let num1 = 1;
      let num2 = 10;
      let num3 = 1000;
      let result = Solution::generate_key(num1, num2, num3);
      assert_eq!(result, 0);
    }

    #[test]
    fn test_2() {
      let num1 = 987;
      let num2 = 879;
      let num3 = 798;
      let result = Solution::generate_key(num1, num2, num3);
      assert_eq!(result, 777);
    }

    #[test]
    fn test_3() {
      let num1 = 1;
      let num2 = 2;
      let num3 = 3;
      let result = Solution::generate_key(num1, num2, num3);
      assert_eq!(result, 1);
    }
}

// Example 1:

// Input: num1 = 1, num2 = 10, num3 = 1000

// Output: 0

// Explanation:

// On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".

// The 1st digit of the key is min(0, 0, 1).
// The 2nd digit of the key is min(0, 0, 0).
// The 3rd digit of the key is min(0, 1, 0).
// The 4th digit of the key is min(1, 0, 0).
// Hence, the key is "0000", i.e. 0.

// Example 2:

// Input: num1 = 987, num2 = 879, num3 = 798

// Output: 777

// Example 3:

// Input: num1 = 1, num2 = 2, num3 = 3

// Output: 1

 