# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        res = {}
        for let in t:
            if let not in s:
                return let
            if let not in res:
                res[let]=1
            else:
                res[let]+=1
        for let in s:
            res[let] -= 1
        for item in res.items():
            if item[1]>0:
                return item[0]

s = Solution()
print(s.findTheDifference('a','aa'))